### ISSUE TITLE
error

### ISSUE THREAD

**Issue by you-old** [hertasecurity/gpu-nms#1]
![image](https://user-images.githubusercontent.com/16161846/90773414-6f13ff80-e328-11ea-94fa-85a48f775fbd.png)

./nmstest detections.txt output.txt

no output detections

**Comment by hertasecurity** [comment]
As it is stated in the README file, if the **SM_ARCH** and **GPU_ARCH** variables in the Makefile **_do not match_** the architecture of your NVIDIA GPU, the kernels will not work as expected.

Please, set up the **SM_ARCH** and **GPU_ARCH** variables accordingly. By default, both Makefile variables are set up for the Tesla T4 (_sm_75_ / _compute_75_).
 
- Example:

If you execute **./nmstest** on a GeForce GTX 1060 (_sm_61_ / _compute_61_), you simply need to update **SM_ARCH = sm_61**  **GPU_ARCH = compute_61** in the Makefile, and then recompile the source code:

```
$ make

gcc -I/usr/local/cuda/include -onmstest.o -c nmstest.c
nvcc -o nms.o -c nms.cu -O3 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=sm_61
gcc -I/usr/local/cuda/include -onmstest nmstest.o nms.o -L/usr/local/cuda/lib64 -lcudart -lcuda


$ ./nmstest detections.txt output.txt

CUDA Runtime Version 11000
Device 0# GeForce GTX 1060 6GB	 [1.71 GHz - 10 Multiprocessors - Core sm_61 - 6071 MB]
Device 0# has been selected for CUDA computation

Detections read from input file (detections.txt): 2997
NMS-MAP elapsed time: 1.202 ms
NMS-REDUCE elapsed time: 0.464 ms
Detections after NMS: 145


$ ./drawrectangles output.txt
```

![oscarsdets](https://user-images.githubusercontent.com/6735670/90826851-7395e380-e33b-11ea-9127-1789930b38d1.png)
